version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 4
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 4
