tasks:
    - init: yarn
    - init: sdk default java 17.0.4.fx-zulu && ./gradlew build
    - init: go test ./...
    - init: cargo test

vscode:
    extensions:
        - rust-lang.rust-analyzer
        - firsttris.vscode-jest-runner
