[workspace]
members = [
    "Array",
    "DP",
    "backtracking",
    "binary_search",
    "bit_manipulation",
    "compiler",
    "sliding_window",
    "String",
    "greedy",
    "linked_list",
    "Tree",
    "trie",
    "stack",
    "Math",
    "priority_queue"
]
