#![allow(dead_code)]

mod _0036_valid_sudoku;
mod _0347_top_k_frequent_elements;
mod _0760_find_anagram_mappings;
mod _1108_defanging_an_ip_address;
mod _1165_single_row_keyboard;
mod _1313_decompress_run_length_encoded_list;
mod _1365_how_many_numbers_are_smaller_than_the_current_number;
mod _1431_kids_with_the_greatest_number_of_candies;
mod _1470_shuffle_the_array;
mod _1480_running_sum_of_1d_array;
mod _1512_number_of_good_pairs;
mod _1528_shuffle_string;
mod _1672_richest_customer_wealth;
mod _1920_build_array_from_permutation;
mod _1929_concatenation_of_array;
mod _2011_final_value_of_variable_after_performing_operations;
mod _2114_maximum_number_of_words_found_in_sentences;
mod _2160_minimum_sum_of_four_digit_number_after_splitting_digits;
mod _2235_add_two_integers;
