#![allow(dead_code)]

mod _0003_length_of_longest_substring;
mod _0005_longest_palindrome;
mod _0159_longest_substring_with_at_most_two_distinc_characters;
mod _0209_minimum_size_subarray_sum;
mod _0217_contains_duplicate;
mod _0438_find_all_anagrams_in_a_string;
mod _0487_max_consecutive_ones_ii;
mod _0567_permutation_in_string;
mod _0643_maximum_average_subarray_i;
mod _1004_max_consecutive_ones_iii;
mod _1052_grumpy_bookstore_owner;
mod _1151_minimum_swaps_to_group_all_1s_together;
mod _1208_get_equal_substrings_within_budget;
mod _1423_maximum_points_you_can_obtain_from_cards;
mod _1695_maximum_erasure_value;
